define: &input_dir 'inputs'
define: &output_dir 'outputs'

proj_mgmt:
  input_dir: *input_dir
  output_dir: *output_dir
  stt_model: 'vosk-models/vosk-model-en-us-0.42-gigaspeech'
  default_video_file_ext: '.mp4'
  default_audio_file_ext: '.wav'

download_yt:
  yt_url: ''
  output_file: 'outputs/filename'
  format: 'mp4'

transcraibe:
  input_file: '/Users/rr/Downloads/trumpbiden2024-1.mp4'
  stt_model: 'vosk-models/vosk-model-en-us-0.42-gigaspeech'

resize:
  input_file: 'inputs/input.mp4'
  output_file: 'outputs/resize.mp4'
  width: 1200
  height: 200

convert:
  input_file: 'inputs/input.mp4'
  output_file: 'outputs/output.mkv'
  format: "avi"

extract_frames:
  input_file: 'inputs/input.mp4'
  output_folder: 'outputs/extract_frames.mp4'
  frame_rate: 24

silence_x:
  input_file: '/Users/rr/Downloads/trumpbiden2024-1.mp4'
  output_file: 'outputs/output.mkv'
  min_d: 0
  max_d: 1000
  adj: 0

extract_sound:
  input_file: 'inputs/input.mp4'
  output_file: 'outputs/extract_sound.wav'

reverse:
  input_file: 'inputs/input.mp4'
  output_file: 'outputs/reverse.mp4'

nostalgic_stutter:
  input_file: 'inputs/input.mp4'
  output_file: 'outputs/nostalgic.mp4'

stutter_pro:
  input_file: 'inputs/input.mp4'
  stutter: "233.4"
  output_file: 'outputs/stutter_pro.mp4'

stack_2x:
  input_file1: 'inputs/input.mp4'
  input_file2: 'inputs/input.mp4'
  output_file: 'outputs/stack_2x.mp4'

lsd_feedback:
  input_file: 'inputs/input.mp4'
  #frame_weights: 1 1 -3 2 1 1 -3 1
  output_file: 'outputs/lsd_feedback.mp4'

frame_delay_pro1:
  input_file: 'inputs/input.mp4'
  # num_of_frames: "10"
  # frame_weights: -2 1 -1 -3 4 1 -3 1 4 1
  num_of_frames: "13"
  frame_weights: -2 1 -1 -3 4 1 -3 1 4 1 3 5 -4
  output_file: 'outputs/frame_delay_pro1.mp4'

frame_delay_pro2:
  input_file: 'inputs/input.mp4'
  decay: "0.92"
  planes: "7"
  output_file: 'outputs/frame_delay_pro2.mp4'

mirror_delay:
  input_file: 'inputs/input.mp4'
  output_file: 'outputs/mirror_delay.mp4'

blur_pix:
  input_file: 'inputs/input.mp4'
  output_file: 'outputs/blur_pix.mp4'

broken_scroll:
  input_file: 'inputs/input.mp4'
  output_file: 'outputs/broken_scroll.mp4'

speed:
  input_file: 'inputs/input.mp4'
  speed_factor: 1.5
  output_file: 'outputs/speed.mp4'  

scrolling_pro:
  input_file: 'inputs/input.mp4'
  # horizontal: "0.003"
  # vertical: "0.006"
  horizontal: "-0.0013"
  vertical: "-0.0016"  
  output_file: 'outputs/scrolling_pro.mp4'

overexposed_stutter:
  input_file: 'inputs/input.mp4'
  output_file: 'outputs/overexposed_stutter.mp4'

